name: Publish
on:
  workflow_dispatch:
    inputs:
      run_deploy:
        description: 'Запустить джобу deploy?'
        required: true
        default: 'false'
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ inputs.run_deploy }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - run: ./scripts/set-version.sh
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}